[workspace]

members = [
    "slosh",
    "compiler",
    "vm",
    "builtins",
    "compile_state",
]

[profile.release]
lto = true
#codegen-units = 1
#opt-level = 'z'
debug = true
#panic = "abort"

