[package]
name = "sl-sh"
version = "0.5.1"
authors = ["Steven Stanfield <stanfield@scarecrowtech.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
liner = { git = "https://gitlab.redox-os.org/redox-os/liner" }
glob = "0.3"
nix = "0.15.0"
libc = "0.2"
# jemallocator = "0.3.0"

[build-dependencies]
chrono = "0.4.7"

