[package]
name = "sl-sh"
version = "0.8.6"
authors = ["Steven Stanfield <stanfield@scarecrowtech.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redox_liner = { git = "https://github.com/sstanfield/liner.git" }
#redox_liner = { path = "../liner" }
glob = "0.3"
nix = "0.15.0"
libc = "0.2"
# jemallocator = "0.3.0"

[build-dependencies]
chrono = "0.4.7"

[profile.release]
lto = true
#opt-level = 'z'

#[dev-dependencies]
#criterion = "0.3"

#[[bench]]
#name = "start_benchmark"
#harness = false

