[package]
name = "slsh"
version = "0.1.0"
authors = ["Steven Stanfield <stanfield@scarecrowtech.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
liner = { git = "https://gitlab.redox-os.org/redox-os/liner" }
glob = "0.3"
