[package]
name = "sl-sh"
version = "0.8.100"
authors = ["Steven Stanfield <stanfield@scarecrowtech.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redox_liner = { git = "https://github.com/sstanfield/liner.git" }
#redox_liner = { path = "../liner" }
glob = "0.3"
nix = "0.15.0"
libc = "0.2"
unicode-segmentation = "1.6.0"
unicode_reader = "1"
#jemallocator = "0.3.2"

[build-dependencies]
chrono = "0.4.7"

[profile.release]
lto = true
#codegen-units = 1
#opt-level = 'z'
#debug = true
panic = "abort"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "start_benchmark"
harness = false

[[bench]]
name = "start_script"
harness = false

