[package]
name = "bridge_macros"
version = "0.1.0"
edition = "2021"


[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.95", features = ["full"] }
quote = "1.0.18"
static_assertions = "1.1.0"
bridge_types = { workspace = true }
trybuild = "1.0.85"
slvm = { path = "../vm" }
