[book]
authors = ["gpwclark", "sstanfield"]
language = "en"
multilingual = false
src = "src"
title = "Slosh Documentation"

#[preprocessor.slosh-eval]
#after = ["links"]

[preprocessor.slosh]
after = ["links"]

[slosh]
blow-up = "blow-up"
