[book]
authors = ["gpwclark", "sstanfield"]
language = "en"
multilingual = false
src = "src"
title = "Slosh Documentation"
slosh-eval-preprocessor = "blow-up"

[preprocessor.slosh-eval]
after = ["links"]
capture-prn = true
