name: Bencher

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  benchmark_pr_with_bencher:
    if: github.event.pull_request.merged == true || github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      pull-requests: write
    name: Continuous Benchmarking with Bencher
    runs-on: ubuntu-latest
    env:
      BENCHER_PROJECT: sl-sh
      BENCHER_TESTBED: ubuntu-latest
      BENCHER_ADAPTER: rust_iai_callgrind
    steps:
      - run: sudo apt-get update
      - run: sudo apt install -y valgrind
      - cargo install --version 0.10.2 iai-callgrind-runner
      - uses: actions/checkout@v4
      - uses: bencherdev/bencher@main
      - name: Install iai-callgrind-runner
        run: |
          version=$(cargo metadata --format-version=1 |\
            jq '.packages[] | select(.name == "iai-callgrind").version' |\
            tr -d '"'
          )
          cargo install iai-callgrind-runner --version $version
      - name: Track Benchmarks with Bencher
        run: |
          bencher run \
          --if-branch "$GITHUB_REF_NAME" \
          --else-if-branch "$GITHUB_BASE_REF" \
          --else-if-branch main \
          --github-actions "${{ secrets.GITHUB_TOKEN }}" \
          --token "${{ secrets.BENCHER_API_TOKEN }}" \
          --err \
          "cargo bench"
