name: Bencher

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

env:
  RUST_BACKTRACE: 1

jobs:
  target_branch:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.get_branch.outputs.branch_name }}
    steps:
      - id: get_branch
        if: github.event.pull_request.merged == true && github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
        run: echo "branch_name=master" >> "$GITHUB_OUTPUT"

  backup_branch:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.get_branch.outputs.branch_name }}
    steps:
      - id: get_branch
        if: github.event.pull_request.merged == true || github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
        run: echo "branch_name=$GITHUB_REF_NAME" >> "$GITHUB_OUTPUT"


  benchmark_pr_with_bencher:
    needs: target_branch
    permissions:
      pull-requests: write
    name: Continuous Benchmarking with Bencher
    runs-on: ubuntu-latest
    env:
      BENCHER_PROJECT: sl-sh
      BENCHER_TESTBED: ubuntu-latest
      BENCHER_ADAPTER: rust_iai_callgrind
      BRANCH: ${{needs.target_branch.outputs.branch_name}}
      BACKUP_BRANCH: ${{needs.backup_branch.outputs.branch_name}}
    steps:
      - run: sudo apt-get update
      - run: sudo apt install -y valgrind
      - uses: actions/checkout@v4
      - uses: bencherdev/bencher@main
      - run: cargo install iai-callgrind-runner --version 0.10.2
      - name: Track Benchmarks with Bencher
        run: |
          echo "Running bencher for branch $BRANCH."
          bencher run \
          --if-branch "$BRANCH" \
          --else-if-branch "$BACKUP_BRANCH" \
          --else-if-branch "$GITHUB_BASE_REF" \
          --github-actions "${{ secrets.GITHUB_TOKEN }}" \
          --token "${{ secrets.BENCHER_API_TOKEN }}" \
          -- branch "${{ github.event.pull_request.base.ref }}"
          --err \
          "cargo bench"
