name: Rust

on:
  push:
  pull_request:

env:
  RUSTFLAGS: -Dwarnings
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Format
      run: |
          cargo version
          rustc --version
          cargo fmt --verbose -- --check
    - name: Clippy
      run: |
          cargo version
          rustc --version
          cargo clippy --verbose -- -D warnings
    - name: Build
      run: |
          cargo version
          rustc --version
          cargo build --workspace --verbose
    - name: Run Rust tests
      run: cargo test --verbose

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
          cargo version
          rustc --version
          cargo build --workspace --verbose
    - name: Run Rust tests
      run: cargo test --verbose
